### ISSUE TITLE
Using a raspberry pi and an android phone simultaneously

### ISSUE THREAD

**Issue by ahaverty** [tzachi-dar/LibreAllHouse#4]
Hi there, I'm just wondering if this project allows my phone to be used as the primary connection to the miaomiao, and also use a raspberry pi as a backup?
I'm having issues keeping my phone connected to my miaomiao overnight, but would be interested in setting up a pi next to my bed.
I'm not sure how many connections miaomiao can hold simultaneously and couldn't find anything in the readme or google doc.
Thank you!

**Comment by tzachi-dar** [comment]
Yes, it does.

On xdrip you can choose hw source as wifi + BT.
In that case xDrip will both try to connect to the MM as well as check for readings in the PI.

The MM itself can only connect to one device simultaneously. 
This is not a problem, since if there are more than one device around it, only one will connect, xDrip will get the data from it and all will be well.

**Comment by ahaverty** [comment]
Awesome. I'll check this out so. This project is also in my wheelhouse of languages, so I should be able to contribute if you have a roadmap. Cheers!
